### ISSUE TITLE
stuck on initial loading

### ISSUE THREAD

**Issue by erickythierry** [emkis/dropbox-clone#10]
I really liked the look and simplicity of your project.
I followed the local installation step by step, however, when starting the project with npm run start, the site is stuck in the initial loading animation. any tips?

**Comment by emkis** [comment]
@erickythierry probably because you didn't define the ENV variable for the API.

The Folders page has a loading state that is initialized with true while the service tries to fetch the available folders. If no folders are founded, you will be stuck with this loading screen forever, because I didn't handle this scenario.

**Comment by erickythierry** [comment]
percebi que vc é BR (hahaha) podemos falar em portugues? 
obrigado pela resposta
percebi que se eu criar a pasta folders no diretorio dos arquivos, o travamento passa, porem nao consigo inserir nenhuma nova pasta pela interface do projeto. eu renomeei o .env.exemple pra .env e rodei localmente e mesmo assim ficou nisso

**Comment by emkis** [comment]
Claro, bora em português, hehe.

Então, como eu mencionei, tu precisa definir o valor da variável da URL da API dentro do arquivo `.env`

Tu pode usar o valor de uma API tua mesmo que esteja rodando localmente, ou a própria URL que está em produção, essa URL está escrita no README do projeto, na parte de Step By Step.

**Comment by erickythierry** [comment]
ahh entendi. analisei novamente o projeto e entendi que ele precisa se conectar a api (projeto a parte). porem o link do repositorio da api ta quebrado. teria o repositorio em outro lugar disponivel?

**Comment by emkis** [comment]
Então na verdade deixei privado esse projeto da API, tu pode tentar criar uma API seguindo a estrutura de comunicação que o Client faz, ou tu pode utilizar a API que utilizo em prod, que é a mesma que mencionei que está no README do projeto
